### ISSUE TITLE
Support „share issue“ workflows

### ISSUE THREAD

**Issue by staabm** [mattermost/mattermost-plugin-jira#131]
In jira it is possible to share a certain ticket to certain users.
This usually triggers a email notification with the given text message.
(See the red box in https://www.google.de/search?q=jira+share+issue&prmd=nisv&source=lnms&tbm=isch&sa=X&ved=2ahUKEwiElebegdPiAhWCCuwKHYwpBZQQ_AUoAnoECAwQAg&biw=1024&bih=634#imgrc=mnsLR2VazD05WM)

It would be great if we could get a mattermost notification instead of such emails, which get often read only once and afterwards will be deleted

**Comment by jasonblais** [comment]
@staabm What if you were able to at-mention the user in a Jira comment, which then posts a message to the user in Mattermost. For instance,

1. Jason adds a comment `@staabm can you help review this ticket` or `@staabm heads up on this ticket` in the Jira issue
2. `staabm` receives a direct message from the Jira plugin with the at-mention and a link to the issue

This would look something like below
![image](https://user-images.githubusercontent.com/13119842/59154033-50815b80-8a37-11e9-9cc8-81c976b6635b.png)

Would this cover the use case you have in mind?

**Comment by staabm** [comment]
In our workflows we use both mentioned use-cases on a regular basis.

Mentioning someone via comment is a big part of the emails. The other big part is my above mentioned share issue feature.

So to answer your question - we would need both things, not only the one you mentioned.

**Comment by jasonblais** [comment]
@staabm Thank you for the feedback, and that makes sense. In the attached screenshot, would you expect to have two options presented - to either send to an email address or to a Mattermost user?

![image](https://user-images.githubusercontent.com/13119842/59165844-0dcf8a00-8af0-11e9-91df-d10f027110c1.png)

**Comment by staabm** [comment]
IMO a user should configure how he would like to receive notifications. The sender should not be required to make a choice about the message medium.

**Comment by jasonblais** [comment]
@staabm Ah, got it. So this particular UI would not change, instead Mattermost would plug in to the Jira notification preferences and enable users to choose between receiving these notifications in email or Mattermost.?

**Comment by staabm** [comment]
Exactly

**Comment by jasonblais** [comment]
@staabm Great. I've drafted a summary of the above conversation. Let me know if this looks good and I can turn this into a help wanted enhancement 👍 

------

**CONTEXT**

In Jira, it is possible to share a specific ticket with certain users.

This triggers an email notification with the given text message.

https://user-images.githubusercontent.com/13119842/59165844-0dcf8a00-8af0-11e9-91df-d10f027110c1.png

(See the red box in https://www.google.de/search?q=jira+share+issue&prmd=nisv&source=lnms&tbm=isch&sa=X&ved=2ahUKEwiElebegdPiAhWCCuwKHYwpBZQQ_AUoAnoECAwQAg&biw=1024&bih=634#imgrc=mnsLR2VazD05WM)

**PROPOSED CHANGE**

Enable users to receive these notifications via Mattermost instead of email.

The exact approach would need to be investigated, but one option is for Mattermost to plug in to the Jira notification preferences and enable users to choose between receiving these notifications in email or Mattermost. The sender would then not be required to make a choice about the message medium.

**Comment by staabm** [comment]
Jep, this sounds great. Thx

**Comment by jasonblais** [comment]
Great, thanks! I reopened it here, we can use that to track the progression of this enhancement 👍 

https://github.com/mattermost/mattermost-plugin-jira/issues/163
