### ISSUE TITLE
Auto-create and link Mattermost channel to JIRA issue

### ISSUE THREAD

**Issue by tomireland** [mattermost/mattermost-plugin-jira#200]
Sorry if this is already available or links to another feature. Please let me know if it does.

It would be great if it was possible to auto-create and link a channel to a JIRA issue.

The use-case for us is we use JIRA Service Desk to speak to our customers and there can also be a lot of internal chatter which takes place around it. Comments in JIRA are pretty terrible at tracking internal and external conversations because there is no proper comment threading, which means comments become fractured.

I thought it would be a good idea to be able to create a Mattermost channel for conversations about a specific issue and auto-link it so an internal discussion can take place there. I guess the current workaround would be to create a channel and link it manually?

Not sure if there is a better way to do it so I am open to ideas/options.

If not, it would be great to see this feature developed.

**Comment by aaronrothschild** [comment]
Tom - I like this idea.  I don't think it's been built by anyone yet.

Yes, as a current workflow today, you'd need to make a channel and send an invite or a permalink to a conversation.

**Comment by aaronrothschild** [comment]
@tomireland - I found out the other day that a partner has created a Jira/Mattermost plugin to connect the two systems kind of as you described:  https://marketplace.atlassian.com/apps/1220414/amplifier-for-mattermost-jira?hosting=server&tab=overview I'll keep this open as a PR since it would be great if we had a way to easily do this out of the box.

**Comment by jprusch** [comment]
I tested the mentioned plugin, but we decided to not use it because of various issues with UI on the Jira side. 
An enhancement with a slash command like
/jira channel KEY-1234 (private)
would be great. This should create a new (private) channel with name KEY-1234. On the Jira side, a comment with a link to the created channel should be attached to KEY-1234.

**Comment by levb** [comment]
Let me summarize the ask here.

1. `/jira [public|private] channel <issue-key>` would create a new channel
2. All known users on the issue will be invited (they need to be connected to Jira in in MM) - assignee, reporter, watchers, etc. Print display names of the users that are not connected, so they can be manually added.
3. A subscription will be created to post updates from the issue
4. (The issue link will be added to the channel header?)

**Comment by jprusch** [comment]
Well, you nailed it! Great & even better functionality that I scribbled up...

**Comment by levb** [comment]
+1 and as a bonus, the whole thing (number 1, really) should be trigger-able from a subscription to begin with (i.e. a create event + filters => start a channel)

**Comment by wiersgallak** [comment]
Closing issues due to inactivity. This issue can be re-opened with more interest from our community.
