### ISSUE TITLE
Created/Attached to a Jira issue message should include a reference to the Jira plugin

### ISSUE THREAD

**Issue by levb** [mattermost/mattermost-plugin-jira#438]
These messages get posted from the acting user, so it's hard to tell that the plugin acted on behalf. We should either add to the text "Created a Jira Issue MM-12345 using the Jira plugin.", or we can change it so that the messages come from the bot, but mention the acting user.

**Comment by levb** [comment]
cc @aaronrothschild

**Comment by AGMETEOR** [comment]
@levb I would like to pick this up. But I don't think I fully get the context. This is because, when I create an issue from mattermost it's labelled "*Issue created from a message in Mattermost.*"
Is that the message that I should alter for this issue?

**Comment by levb** [comment]
cc @aaronrothschild @asaadmahmood 

@AGMETEOR There are 2 messages that the plugin creates here - one that is posted back in the channel/thread (channel message), currently "Created MM-12345", and the comment signature "Issue created from a message in Mattermost". This ticket was specifically about the signature for the channel message.

1/5 we should have a documented best practice for it. Suggest "Created by [Jira](...) plugin".

Clicking on the link - for connected (to Jira) users should redirect them to the conversation with the Bot, if possible; or to the documentation page. For the users who are not yet connected it should connect their account, like other connect links.

**Comment by aaronrothschild** [comment]
Sorry, had wrong Github attached and missed notifications on this.  Agreed with Lev's points above - the intention of this was to educate other users about the Jira plugin and that they can use it themselves to create/assign/transition issues from Mattermost directly. It's to increase the awareness and usage of the jira plugin on an instance of mattermost.

**Comment by AGMETEOR** [comment]
@aaronrothschild thanks. Let me work on this.

**Comment by AGMETEOR** [comment]
Hello @levb , just opened a PR for this issue. Made some observations in regards to implementing some of the discussion points on this thread.

> 1/5 we should have a documented best practice for it. Suggest "Created by Jira plugin".

The message is now "Created Jira issue <Issue Link> by mattermost-jira-plugin"

> Clicking on the link - for connected (to Jira) users should redirect them to the conversation with the Bot, if possible; or to the documentation page. For the users who are not yet connected it should connect their account, like other connect links.

Clicking on *mattermost-jira-plugin* will either redirect you to the docs on plugin repo if you're connected or will attempt to connect you if you're not connected.

I am 4/5 that it's not possible to redirect to the conversation with the Bot. That would require us to know the permalink to that message even before the webhook returns a signal after the issue is created.

cc: @aaronrothschild @jfrerich
