### ISSUE TITLE
Improve Allow users to attach and create Jira issues flag to not require a plugin restart

### ISSUE THREAD

**Issue by jfrerich** [mattermost/mattermost-plugin-jira#567]
### Summary
Currently, if you change the state of `Allow users to attach and create Jira issues in Mattermost` individual users see the new behavior if they refresh but, for all users to see the change the plugin must be disabled and re-enabled.

Can this be improved such that connected would see the change immediately?  

### Original Jira Ticket
https://mattermost.atlassian.net/browse/MM-21340

---
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Plugin: Jira" community channel](https://community.mattermost.com/core/channels/jira-plugin).

New contributors, please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/) and our [Plugins Guide](https://developers.mattermost.com/extend/plugins/).

**Comment by jfrerich** [comment]
Additional context provided in the original ticket from @levb 

> This is not a very useful feature to start with, we mostly bundled it into 2.0 as a precaution because we were concerned about potential effects of the new plugin code on the webapp performance.
> 
> 1/5 we should remove the switch in 2.4

**Comment by mickmister** [comment]
I personally disagree with the notion above of this being not useful. Multiple customers have reported using this, where they either only want subscriptions, or only want create/attach. I think this ticket is valid and is definitely feasible.

We need to support a websocket message that lets the client know the setting has changed, and call the appropriate calls to `registerRootComponent` at runtime. These calls do not need to occur at plugin startup. Any calls to `registerRootComponent` should also store the return value in order to be _unregistered_ if the setting gets disabled at runtime, using [`unregisterComponent`](https://developers.mattermost.com/extend/plugins/webapp/reference/#unregisterComponent).

**Comment by levb** [comment]
> I personally disagree with the notion above of this being not useful. Multiple customers have reported using this, where they either only want subscriptions, or only want create/attach. I think this ticket is valid and is definitely feasible.

@mickmister You may be right. @aaronrothschild: insights?

**Comment by mickmister** [comment]
To follow up on my suggested solution above, we don't necessarily need to conditionally _register_ or unregister components, we can instead just `return null` for the _rendering_ of these components if the config value says to disable the UI components. This config setting should be persisted in redux so the components always have access to this value.

**Comment by wiersgallak** [comment]
Closing issues due to inactivity. This issue can be re-opened with more interest from our community.
