### ISSUE TITLE
Connecting to cloud instance of Jira from Chrome will fail

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-jira#606]
Several developers and I are seeing an issue where mapping a user to Jira Cloud instance from Chrome will fail with the following message:
```
Mattermost failed to recognize your user account. Please make sure third-party cookies are not disabled in your browser settings. Make sure you are signed into Mattermost on https://dkh-local.ngrok.io.
```

It's possible this started occurring after an update of Chrome.    

Jira server does not seem affected by this issue.  

Steps:
- Open a Chrome browser
- Login to Mattermost where there is a Jira Cloud instance installed
- Type /jira connect
- In the new tab that opens, authenticate into Jira cloud

**Observed**: Jira shows the error message above 
**Expected**: Jira show you `Allow Mattermost to connect to your Jira account`  with an `Approve` button

**Comment by ahmaddanialmohd** [comment]
Team, a user confirmed that the issue is also reproducible on **Safari** as well. 

Should we change the title of the bug report to **web browser** in general?

**Comment by mickmister** [comment]
@ahmaddanialmohd I'm not seeing the issue with Safari. Can you verify with them that:
- They have third-party cookies enabled in the Safari browser, which is the `Prevent cross-site tracking` setting here

![image](https://user-images.githubusercontent.com/6913320/91737469-20166780-eb7d-11ea-8ff7-42090c0964da.png)

- They are signed into Mattermost with Safari at the URL that is in the error message (it will be the site URL)

**Comment by mickmister** [comment]
@levb I looked some more into having the Jira Cloud connect process use OAuth. It seems like overkill just to solve this ticket, especially with the added step for the admin to create an app link after installing just for this reason.

I know we already discussed this, but the problem is that the MM session cookie is not present in Jira's iframe due to the SameSite cookie policy disallowing this.

Here's a description of the current flow:

- We generate a secret at runtime to store in a one time store
- We create a JWT containing the user's id and the secret, and to have Jira place it in the URL params when the iframe is loaded
- When the user is loading the iframe, we check:
    - The JWT is valid, and the secret it contains matches what we have tied to the user in the one time store
    - The user's MM session cookie is valid

Shouldn't the first check above suffice? Is the goal to make it so Jira Cloud itself cannot impersonate the MM user? 


https://github.com/mattermost/mattermost-plugin-jira/blob/f2e35fc9b27f305c2308c5cde0429264ddca64d3/server/user_cloud.go#L107-L141
