### ISSUE TITLE
Mention `E20` when showing the enterprise license error

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-jira#764]
When attempting to install multiple Jira instances we show this error message when the MM server does not have an `E20` enterprise license:

"You need an Enterprise License to install multiple Jira instances"

We should instead mention that an `E20` license is necessary

"You need an E20 Enterprise License to install multiple Jira instances"

@aaronrothschild how is this wording?

_Issue created from a [Mattermost message](https://community-daily.mattermost.com/_redirect/pl/r6p9mwp47igqjjppfo15nhy54a) *by `@demmerjn`*._

**Comment by aaronrothschild** [comment]
Thanks @mickmister , that wording is good.  Can you clarify for me the current "test" on the licence?  is it looking for "E20" or "e20 only plugins" as a feature?  I also wonder because the Cloud Licence should also enable the "E20 only plugins" too (ie: Cloud customers have the ability to add multiple jira instances) 

Better wording then is:  "You need an E20 Enterprise License or a Cloud Workspace to access multiple Jira instances via Mattermost"

**Comment by haardikdharma10** [comment]
Hi @mickmister, I had updated this earlier with this [PR](https://github.com/mattermost/mattermost-plugin-jira/pull/726/). I wonder what's wrong here?
cc @aaronrothschild

**Comment by mickmister** [comment]
@haardikdharma10 Indeed you did! Great catch :+1:

Closing issue as it's fixed with https://github.com/mattermost/mattermost-plugin-jira/pull/726. Thanks @haardikdharma10!!

**Comment by mickmister** [comment]
@haardikdharma10 The issue is that we haven't made a release of this plugin for quite some time, so that PR has not been included in a release. We did make a dot release recently, but that just contained bug fixing two commits.
