### ISSUE TITLE
Issues installing Jira plugin on Jira Server 9.1

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-jira#864]
Reported here https://community.mattermost.com/core/pl/pw4gs7imhidaugn4rrjbcgueno

> Are there any known issues with the Jira plugin concerning Jira Server/Datacenter 9.1? It seems that the application link configuration in Jira 9 has nothing to do with the installation instructions displayed in Mattermost. I upgraded our Jira env last weekend because of some security issues & just found out today that I couldn't create any issues from a message anymore (Error 404). So I uninstalled the instance & retried with a new installation. The instructions describe something different from what I see in Jira:

<img width="500px" src="https://user-images.githubusercontent.com/6913320/182637751-71bdb071-7cc9-4976-9405-64c862fd841d.png"/>

First screen:

<img width="500px" src="https://user-images.githubusercontent.com/6913320/182637995-9db91440-cefa-42cc-b263-397ab2e48de8.png"/>

Credentials:

This is a OAuth 2.0 authentication on the Jira side.

<img width="500px" src="https://user-images.githubusercontent.com/6913320/182638061-a81cd23c-a4dd-4dfc-92c6-3ed9fb1d0271.png"/>

When I try the fallback solution from Jira (Create a link to an Atlassian product not an external application) you can configure an OAuth 1.0 connections, but still the needed information from Mattermost is not available:

<img width="500px" src="https://user-images.githubusercontent.com/6913320/182638224-d9df00a5-82bf-4e47-8fb6-3f132c131827.png"/>

**Comment by jprusch** [comment]
Apart from the authentication issue, the REST endpoint rest/api/2/issue/createmeta has been removed in Jira 9, which, if use, makes creating Jira issues using REST not working anymore.
Please check:
https://confluence.atlassian.com/jiracore/createmeta-rest-endpoint-to-be-removed-975040986.html

**Comment by jprusch** [comment]
@mickmister @catalintomai Shall I create a new issue for the removal of the REST createmeta endpoint?

**Comment by catalintomai** [comment]
@jprusch, yes, please do. Thanks!

**Comment by jprusch** [comment]
Done #865

**Comment by jprusch** [comment]
@catalintomai Is there a timeframe for this issue? Right now Mattermost is not compatible with Jira 9 (Datacenter/Server) with the aspect of creating issues or commenting. Given that Atlassian security issues might lead to an increased upgrade rate to Jira 9, this might become more imminent. Many companies use Mattermost on premise because of security concerns, same is true for hosting Jira on-prem.

**Comment by christiaanvaken** [comment]
Any update?

**Comment by jprusch** [comment]
This issue is clearly documentation related & has now been solved with some help from Mattermost.
* Make sure you created an ATLASSIAN application link
* Ignore errors on the URL
* On the "Link application" dialog, just enter the name (Mattermost) and select "Create incoming link". Leave all other fields empty
* On the next page enter the data (public key...)

For more context you might want to read

https://community.mattermost.com/core/pl/pw4gs7imhidaugn4rrjbcgueno

in the Mattermost community

**Comment by raghavaggarwal2308** [comment]
> This issue is clearly documentation related & has now been solved with some help from Mattermost.

Closing as completed
