### ISSUE TITLE
Unable to uninstall server

### ISSUE THREAD

**Issue by StepKie** [mattermost/mattermost-plugin-jira#902]
`/jira instance list` returns 

<img width="515" alt="image" src="https://user-images.githubusercontent.com/17760200/210748253-52f3b28d-44f6-40c3-9d98-090ab002bb6f.png">

but when I do `/jira uninstall server https://jira.jpsc.intern`, I get

<img width="312" alt="image" src="https://user-images.githubusercontent.com/17760200/210748535-c33f1582-7565-4c17-83f6-7853fb6dce96.png">

I can not find a way to remove this server (the URL is no longer online), and thus can not connect to a new (cloud) instance in the mattermost free version.
Enabling/Disabling the plugin or uninstalling/reinstalling does not help.

**Comment by jprusch** [comment]
Did you try 

/jira instance uninstall server https://jira.jpsc.intern

**Comment by Hottemax** [comment]
> Did you try
> 
> /jira instance uninstall server https://jira.jpsc.intern

Yes, I get the error message shown above.

**Comment by jprusch** [comment]
Maybe @DHaussermann or @mickmister can help on this one.

**Comment by Hottemax** [comment]
Funnily enough, I also can't unalias it:

`jira unalias https://jira.jpsc.intern`
`jira instance list`

gives 

<img width="763" alt="image" src="https://user-images.githubusercontent.com/17760200/215466765-7997399d-120f-4396-a5d6-8695e9151f14.png">

Maybe there is an easy way to reset the entire jira plugin?

**Comment by mickmister** [comment]
@Hottemax There's currently no way to forcibly reset the plugin, other than doing manual database queries to remove entries of the `PluginKeyValueStore` table, which I don't recommend due to the risks of messing with data integrity.

I'm not sure how your instance got into its current state. We'll do some investigation to try and gather some data about this.

**Comment by Kshitij-Katiyar** [comment]
@mickmister I have tried to reproduce this error by installing the local Jira server, stopping the server, and then trying to uninstall it. It worked fine for me. Same with alias and unalias command. Can you tell me the steps to reproduce the error and further information to fix it?

**Comment by mickmister** [comment]
@Kshitij-Katiyar Unfortunately it's not clear what the steps are to reproduce. I would say that we need to figure out how a given instance can simultaneously:

- show in the `instance list` command's output
- and show the "not found" error in the `instance list` command's output

What code paths allow for this to occur?

**Comment by Kshitij-Katiyar** [comment]
@mickmister I am able to reproduce this issue. 
![Screenshot from 2023-02-09 14-44-34](https://user-images.githubusercontent.com/90389917/217769018-b8a0807f-2943-4968-a593-6b2516597b9f.png)
In the ```/jira instance list``` command there are mainly 2 function calls that interact with the plugin KV store:-
1) LoadInstances - This will return the list of instances installed for the plugin.
2)LoadInstance - This will take an instance_id and return the instance based on that id.

In the list command, they first call the LoadInstances function to get the list of instances. Then iterate over the keys of all the instances installed and call the LoadInstance method for each key.
So this error is coming from the LoadInstance method mainly due to the fact that during installation or by some other method the Key-Value pair for this particular instance got deleted from the plugin store with key ```jira_instance_<hashkey>``` but the instance_id is still present in the array of Instances returned by LoadInstances method.
So whenever this LoadInstance method is getting called with this instance_id as the argument ```not found``` error will be returned. Same is the case with ```/jira instance unalias``` command as this also calls the LoadInstance method.

Steps to reproduce the issue:-
1) Install the Jira server ```/jira instance install server <url>``` command.
2) Copy the hash key from the server logs. Example ```jira_instance_<hashkey>```
3) Add an alias for the server using ```/jira instance alias``` command.
4) Delete the entry for key copied above from plugin store (Can be done using pluginAPI method or directly from DB).
5) Run ```/jira instance list``` command.

Please give your views and suggestions on this.

**Comment by mickmister** [comment]
> Delete the entry for key copied above from plugin store (Can be done using pluginAPI method or directly from DB).

@Kshitij-Katiyar What is your theory for how @Hottemax got his plugin in its current state, and how can we remedy the situation using changes to the source code?

He is wanting to uninstall a Jira instance but the plugin is allowing him to do so because it says it can't find the instance

**Comment by Kshitij-Katiyar** [comment]
@mickmister I think the solution for this could be that when we are uninstalling an instance if it is not found in the KV store. Then we can also check the array of instances installed if it is present there we can delete that entry and I think this would help us in maintaining the consistency between the instances installed array and the KV store.

> What is your theory for how @Hottemax got his plugin in its current state
My Theory is the functions storeInstance and storeInstances both get called if we want to alias an instance. Maybe while running that command there could be some error that prevented it to be stored in KVstore.

**Comment by mickmister** [comment]
@Kshitij-Katiyar Okay that all sounds good to me :+1:
