### ISSUE TITLE
Help Wanted: `/jira setup` missing from some documentation

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-jira#987]
This was originally reported in https://github.com/mattermost/mattermost-plugin-jira/issues/985#issuecomment-1766364908 when discussing this command. The admin configuring the plugin said they didn't know about the command because it isn't documented. There are a few places I would expect this to exist:

- [x] In the README in the configuration step - done [here](https://github.com/mattermost/mattermost-plugin-jira/blob/d1e233af901f5a4c3b652fee260857c74d1c6d44/readme.md?plain=1#L89)
- [x]  In the README in the list of available commands - not done, but should be [here](https://github.com/mattermost/mattermost-plugin-jira/blob/d1e233af901f5a4c3b652fee260857c74d1c6d44/readme.md?plain=1#L125)
- [x] In the plugin's command autocomplete - done [here](https://github.com/mattermost/mattermost-plugin-jira/blob/d1e233af901f5a4c3b652fee260857c74d1c6d44/server/command.go#L334-L335)
- [x] In the plugin's command help text - not done, but should be [here](https://github.com/mattermost/mattermost-plugin-jira/blob/d1e233af901f5a4c3b652fee260857c74d1c6d44/server/command.go#L82)

**Comment by mickmister** [comment]
@elrancid Is there any other documentation you would expect `/jira setup` to be mentioned? It's currently mentioned in the README here https://github.com/mattermost/mattermost-plugin-jira#step-1-configure-the-plugin-in-mattermost, though not in the main list of commands in the README.

**Comment by frantic-rabbit** [comment]
Hey @mickmister, issue description is not clear to me. Can you please elaborate it a bit more?

**Comment by elrancid** [comment]
@mickmister I had seen that documentation, however it is a bit obscure and I thought it needed updating because:
1.ii.) Generate a Secret for Webhook Secret and Stats API Secret:
only Webhook Secret appears in the configuration and not Stats API Secret.
4.) Run /jira setup to start configuring the plugin.
Here the bot indicates the operations to be performed, but there are no indications on these operations. In particular:
1. Choose your Jira edition.
I don't understand where I should choose the edition.
2. Create an incoming application link.
Does this refer to `/jira instance install cloud (url)` even though it is deprecated? Shouldn't it be `/jira instance install cloud-oauth (url)`?

Lastly the link to the documentation doesn't work: https://mattermost.gitbook.io/plugin-confluence/plugin-jira/setting-up/configuration

**Comment by mickmister** [comment]
cc @cwarnermm It seems the documentation on setting up the plugin has some stale information, including steps on installing through the deprecated `cloud` install method. There is also a broken docs link in the README pointing to gitbook

> Choose your Jira edition.
> I don't understand where I should choose the edition.

This is essentially "choose whether you're using Jira Server or Jira Cloud" with the interactive buttons in the next post. Does the setup flow make sense with this in mind?

> Create an incoming application link.
> Does this refer to `/jira instance install cloud (url)` even though it is deprecated? Shouldn't it be `/jira instance install cloud-oauth (url)`?

Yes this should be removed from the setup

**Comment by mickmister** [comment]
@elrancid Thanks for reporting this information :+1:

**Comment by cwarnermm** [comment]
Yes, thank you, @elrancid, for sharing your feedback to improve the user's experience.

**Comment by cwarnermm** [comment]
@frantic-rabbit - If you're open to picking up this ticket, I'm happy to answer any questions you have from a docs perspective. Feel free to reach out via the Mattermost Community Server.

**Comment by Kshitij-Katiyar** [comment]
I created https://github.com/Brightscout/mattermost-plugin-jira/pull/89 to add `/jira setup` to the system admin help text.
